<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita7964865be64897ca9d2062d316fc334
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Config' => __DIR__ . '/../..' . '/model/config.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/rotas.class.php',
        'Template' => __DIR__ . '/../..' . '/model/template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita7964865be64897ca9d2062d316fc334::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita7964865be64897ca9d2062d316fc334::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita7964865be64897ca9d2062d316fc334::$classMap;

        }, null, ClassLoader::class);
    }
}
