<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita7964865be64897ca9d2062d316fc334
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twig\\' => 5,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
        ),
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Config' => __DIR__ . '/../..' . '/model/config.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/rotas.class.php',
        'Template' => __DIR__ . '/../..' . '/model/template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita7964865be64897ca9d2062d316fc334::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita7964865be64897ca9d2062d316fc334::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInita7964865be64897ca9d2062d316fc334::$prefixesPsr0;
            $loader->classMap = ComposerStaticInita7964865be64897ca9d2062d316fc334::$classMap;

        }, null, ClassLoader::class);
    }
}
